@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Nov 06 20:01:17 +0800 2023
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_overall_func_synth -key {Post-Synthesis:sim_1:Functional:tb_overall} -tclbatch tb_overall.tcl -view F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/tb_fft_behav.wcfg -view F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/tb_multiplier_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
