# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/energy_detection_fixed_th.xdc

# IP: ip/adder/adder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet
