# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.cache/wt [current_project]
set_property parent.project_path F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Users/Lenovo/Desktop/flip_t.v
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/flip_t_wrapper.v
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/jtag_mac.v
}
read_vhdl -library xil_defaultlib {
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/jtag_mac_fifo_wrapper.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_bus2dut.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_chifcore.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_chiftop.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_controller.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_dpscram.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_dut2bus.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/mwfil_udfifo.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/simcycle_fifo_wrapper.vhd
  F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/flip_t_fil.vhd
}
read_ip -quiet f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc]

read_ip -quiet f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc]

read_ip -quiet f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/flip_t_fil.xdc
set_property used_in_implementation false [get_files F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/filsrc/flip_t_fil.xdc]


synth_design -top flip_t_fil -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef flip_t_fil.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file flip_t_fil_utilization_synth.rpt -pb flip_t_fil_utilization_synth.pb"
