# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/matlab/slxTest/unclockenable_flip_t_fil/fpgaproj/flip_t_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
