# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/energy_detection_2.srcs/sources_1/ip/rom_32x1024/rom_32x1024.xci
# IP: The module: 'rom_32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/energy_detection_2.srcs/sources_1/ip/rom_32x1024/rom_32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_32x1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/energy_detection_2.srcs/sources_1/ip/rom_32x1024/rom_32x1024.xci
# IP: The module: 'rom_32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Users/Lenovo/Desktop/fpga_zynq/energy_detection_2/vivado_prj/energy_detection_2.srcs/sources_1/ip/rom_32x1024/rom_32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
